### ISSUE TITLE
Add a Help Center or FAQ Section

### ISSUE THREAD

**Issue by Somberous** [Somberous/Passel#8]
## User Story

As a user, I want to access helpful resources and answers to common questions in the application.

## Acceptance Criteria

-     Users can access a Help Center or FAQ section within the application.
-     Help Center or FAQ contains relevant articles, guides, and answers to common questions.
-     Users can search for specific topics or browse categories within the Help Center or FAQ.
-     Users can submit question if it has not been answered before.

## Additional information

- Implement a Help Center or FAQ section to assist users with their questions and concerns.
- This page should be added as another separate page to the application.
- If no solution exists, allow users to submit a question.

## Task

- [ ]  Design Help Center or FAQ UI components
- [ ]  Implement search functionality for Help Center or FAQ
- [ ]  Implement question submission feature
- [ ]  Create and organize content for the Help Center or FAQ
- [ ]  Integrate Help Center or FAQ with the main application
- [ ]  Test Help Center or FAQ functionality and user experience

**Comment by Somberous** [comment]
Created wiki within the repository which will be utilized for the Wiki/Help. This is on the home page of the application. New things will be added to the wiki over time.
